version: "3.9"

services:
  server:
    build: ./server
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - DB_NAME=freelance_db
      - FLASK_APP=app.main
      - FLASK_ENV=development

  web:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:80"  # 80 в контейнере, 3000 для доступа снаружи
    depends_on:
      - server

  mongo:
    image: mongo:8.0.5
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
